### ISSUE TITLE
Could not find artifact org.apache.flink:flink-connector-kafka-083:jar

### ISSUE THREAD

**Issue by wangyangjun** [project-flink/flink-perf#6]
As the title, when I tried to run ‘maven package' under the root project, I got this error.

**Comment by aljoscha** [comment]
I'm looking into the issue.

**Comment by aljoscha** [comment]
Hi,
I updated the code to make it work with the recent changes in 0.10-SNAPSHOT of Flink. Could you please check if it works for you now and close the issue?

**Comment by wangyangjun** [comment]
Hi,
I saw the updates in the code. It fixed my problem. Thanks for help
